spring:
  application:
    name: jvmfy-config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_FILE_URL}
          username: ${GIT_LOGIN}
          password: ${GIT_PASSWORD}
          clone-on-start: true

        native:
          search-locations: classpath:config/

  rabbitmq: #hit the /actuator/bus-refresh (post) url to emit new property
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh