spring:
  application:
    name: JvmfyConfigServer

  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_SERVER}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          clone-on-start: true

server:
  port: 8012